#!/bin/sh

STATE=$(acpi | cut -d ' ' -f 3 | sed 's/,//')
PERCENTAGE=$(acpi | awk '{ print $4 }' | egrep -o '\w+')

if [[ $STATE = "Full" ]]; then
  echo ""
elif [[ $STATE = "Charging" ]]; then
  if [[ $PERCENTAGE -gt 90 ]]; then
    echo ""
  elif [[ $PERCENTAGE -gt 80 ]]; then
    echo ""
  elif [[ $PERCENTAGE -gt 70 ]]; then
    echo ""
  elif [[ $PERCENTAGE -gt 60 ]]; then
    echo ""
  elif [[ $PERCENTAGE -gt 50 ]]; then
    echo ""
  elif [[ $PERCENTAGE -gt 40 ]]; then
    echo ""
  elif [[ $PERCENTAGE -gt 30 ]]; then
    echo ""
  elif [[ $PERCENTAGE -gt 20 ]]; then
    echo ""
  elif [[ $PERCENTAGE -gt 10 ]]; then
    echo ""
  else
    echo ""
  fi
elif [[ $STATE = "Discharging" ]]; then
  if [[ $PERCENTAGE -gt 90 ]]; then
    echo ""
  elif [[ $PERCENTAGE -gt 80 ]]; then
    echo ""
  elif [[ $PERCENTAGE -gt 70 ]]; then
    echo ""
  elif [[ $PERCENTAGE -gt 60 ]]; then
    echo ""
  elif [[ $PERCENTAGE -gt 50 ]]; then
    echo ""
  elif [[ $PERCENTAGE -gt 40 ]]; then
    echo ""
  elif [[ $PERCENTAGE -gt 30 ]]; then
    echo ""
  elif [[ $PERCENTAGE -gt 20 ]]; then
    echo ""
  elif [[ $PERCENTAGE -gt 10 ]]; then
    echo ""
  else
    echo ""
  fi
fi
