#!/bin/sh

MUTE=$(amixer sget Master | egrep "\[on\]")
VOL=$(amixer sget Master | tail -n 1 | egrep -o '\[[0-9]+%\]' | egrep -o '[0-9]+')

if [[ -z $MUTE ]]; then
  echo ""
fi

if [[ $VOL -gt 95 ]]; then
  echo "==========|"
elif [[ $VOL -gt 85 ]]; then
  echo "=========|="
elif [[ $VOL -gt 75 ]]; then
  echo "========|=="
elif [[ $VOL -gt 65 ]]; then
  echo "=======|==="
elif [[ $VOL -gt 55 ]]; then
  echo "======|===="
elif [[ $VOL -gt 45 ]]; then
  echo "=====|====="
elif [[ $VOL -gt 35 ]]; then
  echo "====|======"
elif [[ $VOL -gt 25 ]]; then
  echo "===|======="
elif [[ $VOL -gt 15 ]]; then
  echo "==|========"
elif [[ $VOL -gt 5 ]]; then
  echo "=|========="
else
  echo "|=========="
fi
