#!/bin/sh

MUTE=$(amixer sget Master | egrep "\[on\]")
VOL=$(amixer sget Master | tail -n 1 | awk '{ print $4 }' | egrep -o '[0-9]+')
LABEL="VOL"

if [[ -z $MUTE ]]; then
  echo "."
fi

if [[ $VOL -gt 95 ]]; then
  echo "==========|"
elif [[ $VOL -gt 85 ]]; then
  echo "=========|="
  echo "$LABEL 90"
elif [[ $VOL -gt 75 ]]; then
  echo "========|=="
  echo "$LABEL 80"
elif [[ $VOL -gt 65 ]]; then
  echo "=======|==="
  echo "$LABEL 70"
elif [[ $VOL -gt 55 ]]; then
  echo "======|===="
  echo "$LABEL 60"
elif [[ $VOL -gt 45 ]]; then
  echo "=====|====="
  echo "$LABEL 50"
elif [[ $VOL -gt 35 ]]; then
  echo "====|======"
  echo "$LABEL 40"
elif [[ $VOL -gt 25 ]]; then
  echo "===|======="
  echo "$LABEL 30"
elif [[ $VOL -gt 15 ]]; then
  echo "==|========"
  echo "$LABEL 20"
elif [[ $VOL -gt 5 ]]; then
  echo "=|========="
  echo "$LABEL 10"
else
  echo "|=========="
  echo "$LABEL 0"
fi
