#!/bin/sh

STATE=$(acpi | cut -d ' ' -f 3 | sed 's/,//')
PERCENTAGE=$(acpi | awk '{ print $4 }' | egrep -o '\w+')
TEXT=":$PERCENTAGE%"

if [[ $STATE = "Full" ]]; then
  echo "$TEXT"
elif [[ $STATE = "Charging" ]] || [[ $STATE = "Unknown" ]]; then
  if [[ $PERCENTAGE -gt 90 ]]; then
    echo "$TEXT"
  elif [[ $PERCENTAGE -gt 80 ]]; then
    echo "$TEXT"
  elif [[ $PERCENTAGE -gt 70 ]]; then
    echo "$TEXT"
  elif [[ $PERCENTAGE -gt 60 ]]; then
    echo "$TEXT"
  elif [[ $PERCENTAGE -gt 50 ]]; then
    echo "$TEXT"
  elif [[ $PERCENTAGE -gt 40 ]]; then
    echo "$TEXT"
  elif [[ $PERCENTAGE -gt 30 ]]; then
    echo "$TEXT"
  elif [[ $PERCENTAGE -gt 20 ]]; then
    echo "$TEXT"
  elif [[ $PERCENTAGE -gt 10 ]]; then
    echo "$TEXT"
  else
    echo "$TEXT"
  fi
elif [[ $STATE = "Discharging" ]]; then
  if [[ $PERCENTAGE -gt 90 ]]; then
    echo "$TEXT"
  elif [[ $PERCENTAGE -gt 80 ]]; then
    echo "$TEXT"
  elif [[ $PERCENTAGE -gt 70 ]]; then
    echo "$TEXT"
  elif [[ $PERCENTAGE -gt 60 ]]; then
    echo "$TEXT"
  elif [[ $PERCENTAGE -gt 50 ]]; then
    echo "$TEXT"
  elif [[ $PERCENTAGE -gt 40 ]]; then
    echo "$TEXT"
  elif [[ $PERCENTAGE -gt 30 ]]; then
    echo "$TEXT"
  elif [[ $PERCENTAGE -gt 20 ]]; then
    echo "$TEXT"
  elif [[ $PERCENTAGE -gt 10 ]]; then
    echo "$TEXT"
  else
    echo "$TEXT"
  fi
fi
