#!/bin/bash
 
PACKAGES=$(pacman -Sup | wc -l)

if [[ $PACKAGES != 0 ]]; then
  echo "$PACKAGES updates available"
fi

if [[ $BLOCK_BUTTON = 1 ]]; then
  i3-msg exec "st -e ~/.rice/misc/sys_upgrade.sh"
fi
