#!/bin/bash
 
if [[ $BLOCK_BUTTON = 1 ]]; then
  i3-msg exec "st -e ~/.rice/misc/sys_upgrade.sh" > /dev/null
fi

PACKAGES=$(pacman -Sup | wc -l)

if [[ $PACKAGES = 1 ]]; then
  echo "$PACKAGES update available"
elif [[ $PACKAGES > 1 ]]; then
  echo "$PACKAGES updates available"
fi

