#!/bin/sh

MUTE=$(amixer sget Master | egrep "\[on\]")
VOL=$(amixer sget Master -M | tail -n 1 | egrep -o '\[[0-9]+%\]' | egrep -o '[0-9]+')

if [[ -z $MUTE ]]; then
  echo ""
fi

if [[ $VOL -ge 95 ]]; then
  echo "==========|"
elif [[ $VOL -ge 85 ]]; then
  echo "=========|="
elif [[ $VOL -ge 75 ]]; then
  echo "========|=="
elif [[ $VOL -ge 65 ]]; then
  echo "=======|==="
elif [[ $VOL -ge 55 ]]; then
  echo "======|===="
elif [[ $VOL -ge 45 ]]; then
  echo "=====|====="
elif [[ $VOL -ge 35 ]]; then
  echo "====|======"
elif [[ $VOL -ge 25 ]]; then
  echo "===|======="
elif [[ $VOL -ge 15 ]]; then
  echo "==|========"
elif [[ $VOL -ge 5 ]]; then
  echo "=|========="
else
  echo "|=========="
fi
